# Generated by Django 6.0 on 2026-01-10 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_remove_completedeventimage_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('running', 'Running Event'), ('upcoming', 'Upcoming Event'), ('past', 'Past Event'), ('completed', 'Recently Completed Event'), ('fine_dining', 'Fine Dining & Signature Experiences'), ('live_music', 'Live Music Shows & Unforgettable Memories'), ('fine_dining_2', 'Fine Dining & Signature Experiences (Second)'), ('gallery', 'All Event Photos')], max_length=50)),
                ('event_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventsimage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='heroimage',
            name='hero',
        ),
        migrations.CreateModel(
            name='CompletedEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Recently Completed Event',
                'verbose_name_plural': 'Recently Completed Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
            ],
            options={
                'verbose_name': 'All Event Photos',
                'verbose_name_plural': 'All Event Photos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='FineDining',
            fields=[
            ],
            options={
                'verbose_name': 'Fine Dining & Signature Experiences',
                'verbose_name_plural': 'Fine Dining Experiences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='FineDiningSecond',
            fields=[
            ],
            options={
                'verbose_name': 'Fine Dining (Second Section)',
                'verbose_name_plural': 'Fine Dining (Second Section)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='LiveMusic',
            fields=[
            ],
            options={
                'verbose_name': 'Live Music Shows & Memories',
                'verbose_name_plural': 'Live Music Shows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='PastEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Past Event',
                'verbose_name_plural': 'Past Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='RunningEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Running Event',
                'verbose_name_plural': 'Running Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Upcoming Event',
                'verbose_name_plural': 'Upcoming Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='EventsImage',
        ),
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
