# Generated by Django 6.0 on 2026-01-10 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_remove_eventsimage_event_remove_heroimage_hero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('running', 'Running Event'), ('upcoming', 'Upcoming Event'), ('past', 'Past Event'), ('completed', 'Recently Completed Event'), ('fine_dining', 'Fine Dining & Signature Experiences'), ('live_music', 'Live Music Shows & Unforgettable Memories'), ('fine_dining_2', 'Fine Dining (Second Section)'), ('gallery', 'All Event Photos')], db_index=True, max_length=50),
        ),
    ]
