# Generated by Django 6.0 on 2026-01-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_created_at_event_is_active_event_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField(blank=True, null=True)),
                ('hero_image', models.ImageField(upload_to='events/images/')),
                ('event_type', models.CharField(choices=[('running', 'Running Event'), ('upcoming', 'Upcoming Event'), ('past', 'Past Event')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastEventHero',
            fields=[
            ],
            options={
                'verbose_name': 'Past Event',
                'verbose_name_plural': 'Past Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.eventhero',),
        ),
        migrations.CreateModel(
            name='RunningEventHero',
            fields=[
            ],
            options={
                'verbose_name': 'Running Event',
                'verbose_name_plural': 'Running Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.eventhero',),
        ),
        migrations.CreateModel(
            name='UpcomingEventHero',
            fields=[
            ],
            options={
                'verbose_name': 'Upcoming Event',
                'verbose_name_plural': 'Upcoming Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.eventhero',),
        ),
    ]
