# Generated by Django 6.0 on 2026-01-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventhero_pasteventhero_runningeventhero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasteventhero',
            options={'verbose_name': 'Past Event Hero', 'verbose_name_plural': 'Past Events Hero'},
        ),
        migrations.AlterModelOptions(
            name='runningeventhero',
            options={'verbose_name': 'Running Event Hero', 'verbose_name_plural': 'Running Events Hero'},
        ),
        migrations.AlterModelOptions(
            name='upcomingeventhero',
            options={'verbose_name': 'Upcoming Event Hero', 'verbose_name_plural': 'Upcoming Event Hero'},
        ),
        migrations.AlterField(
            model_name='eventhero',
            name='event_type',
            field=models.CharField(choices=[('running', 'Running Event Hero'), ('upcoming', 'Upcoming Event Hero'), ('past', 'Past Event Hero')], db_index=True, max_length=20),
        ),
    ]
