# Generated by Django 6.0 on 2026-01-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_pasteventhero_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningeventhero',
            options={'verbose_name': 'Running Event Hero', 'verbose_name_plural': 'Running Event Heroes'},
        ),
        migrations.AlterModelOptions(
            name='upcomingeventhero',
            options={'verbose_name': 'Upcoming Event Hero', 'verbose_name_plural': 'Upcoming Event Heroes'},
        ),
    ]
