# Generated by Django 6.0 on 2026-01-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_runningeventhero_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEventPhoto',
            fields=[
            ],
            options={
                'verbose_name': 'Past Event Photo',
                'verbose_name_plural': 'Past Event Photos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('running', 'Running Event'), ('upcoming', 'Upcoming Event'), ('past', 'Past Event'), ('past_photo', 'Past Event Photo'), ('completed', 'Recently Completed Event'), ('fine_dining', 'Fine Dining & Signature Experiences'), ('live_music', 'Live Music Shows & Unforgettable Memories'), ('fine_dining_2', 'Fine Dining (Second Section)'), ('gallery', 'All Event Photos')], db_index=True, max_length=50),
        ),
    ]
