# Generated by Django 5.2.8 on 2026-02-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_pasteventphoto_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasteventhero',
            options={'verbose_name': 'Past Event Hero', 'verbose_name_plural': 'Past Event Heroes'},
        ),
    ]
