# Generated by Django 5.2.8 on 2026-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_pasteventhero_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningEventSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/running/slider/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Running Event Slider Image',
                'verbose_name_plural': 'Running Event Slider Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
