# Generated by Django 5.2.8 on 2026-03-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_runningeventslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMusicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='events/images/')),
                ('image_type', models.CharField(choices=[('gallery_1', 'Gallery 1'), ('gallery_2', 'Gallery 2'), ('gallery_3', 'Gallery 3')], default='gallery_1', max_length=20)),
                ('live_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_music_images', to='events.livemusic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
