# Generated by Django 6.0 on 2026-01-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('place_type', models.CharField(choices=[('swimming_pool', 'Swimming Pool'), ('billiard_smoking', 'Billiard & Smoking'), ('library', 'Library'), ('beauty_parlor', 'Beauty Parlor'), ('laundry', 'Laundry'), ('card_room', 'Card Room'), ('banquet_hall', 'Banquet Hall')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BanquetHall',
            fields=[
            ],
            options={
                'verbose_name': 'Banquet Hall',
                'verbose_name_plural': 'Banquet Halls',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='BeautyParlor',
            fields=[
            ],
            options={
                'verbose_name': 'Beauty Parlor',
                'verbose_name_plural': 'Beauty Parlors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='BilliardSmoking',
            fields=[
            ],
            options={
                'verbose_name': 'Billiard & Smoking',
                'verbose_name_plural': 'Billiard & Smoking',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='CardRoom',
            fields=[
            ],
            options={
                'verbose_name': 'Card Room',
                'verbose_name_plural': 'Card Rooms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
            ],
            options={
                'verbose_name': 'Laundry',
                'verbose_name_plural': 'Laundry',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='SwimmingPool',
            fields=[
            ],
            options={
                'verbose_name': 'Swimming Pool',
                'verbose_name_plural': 'Swimming Pools',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='PlaceHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='places/highlights/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='facilities.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/images/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='places/offers/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='facilities.place')),
            ],
        ),
    ]
