# Generated by Django 6.0 on 2026-01-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungesParty',
            fields=[
            ],
            options={
                'verbose_name': 'Lounges Party',
                'verbose_name_plural': 'Lounges Partys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('lounges_party', 'Lounges Party'), ('swimming_pool', 'Swimming Pool'), ('billiard_smoking', 'Billiard & Smoking'), ('library', 'Library'), ('beauty_parlor', 'Beauty Parlor'), ('laundry', 'Laundry'), ('card_room', 'Card Room'), ('banquet_hall', 'Banquet Hall')], max_length=50),
        ),
    ]
