# Generated by Django 6.0 on 2026-01-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_loungesparty_alter_place_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='healthcare_gym',
            fields=[
            ],
            options={
                'verbose_name': 'healthcare_gym',
                'verbose_name_plural': 'healthcare_gym',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.CreateModel(
            name='salon',
            fields=[
            ],
            options={
                'verbose_name': 'salon',
                'verbose_name_plural': 'salon',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('facilities.place',),
        ),
        migrations.AlterModelOptions(
            name='loungesparty',
            options={'verbose_name': 'Lounges Party', 'verbose_name_plural': 'Lounges Party'},
        ),
        migrations.AlterModelOptions(
            name='swimmingpool',
            options={'verbose_name': 'Swimming Pool', 'verbose_name_plural': 'Swimming Pool'},
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('healthcare_gym', 'Healthcare & Gym'), ('salon', 'Salon'), ('lounges_party', 'Lounges Party'), ('swimming_pool', 'Swimming Pool'), ('billiard_smoking', 'Billiard & Smoking'), ('library', 'Library'), ('beauty_parlor', 'Beauty Parlor'), ('laundry', 'Laundry'), ('card_room', 'Card Room'), ('banquet_hall', 'Banquet Hall')], max_length=50),
        ),
    ]
