# Generated by Django 5.2.8 on 2026-02-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_healthcare_gym_salon_alter_loungesparty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcare_gym',
            options={'verbose_name': 'Healthcare & Gym', 'verbose_name_plural': 'Healthcare & Gym'},
        ),
        migrations.AlterModelOptions(
            name='laundry',
            options={'verbose_name': 'Laundry', 'verbose_name_plural': 'Laundry Services'},
        ),
        migrations.AlterModelOptions(
            name='loungesparty',
            options={'verbose_name': 'Lounges Party', 'verbose_name_plural': 'Lounges Parties'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Salon', 'verbose_name_plural': 'Salons'},
        ),
        migrations.AlterModelOptions(
            name='swimmingpool',
            options={'verbose_name': 'Swimming Pool', 'verbose_name_plural': 'Swimming Pools'},
        ),
    ]
