# Generated by Django 5.2.8 on 2025-12-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('board_of_director', 'Board of Director'), ('executive_member', 'Executive Member'), ('founder_member', 'Founder Member')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='board_members/')),
                ('member_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('member_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='about.membertype')),
            ],
        ),
    ]
