# Generated by Django 5.2.8 on 2025-12-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutForHeritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='About/gallery')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='About/about_us')),
            ],
        ),
        migrations.CreateModel(
            name='Bottomgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='About/gallery')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='About/gallery')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='member_image',
            field=models.ImageField(upload_to='About/board_members/'),
        ),
    ]
