# Generated by Django 5.2.8 on 2025-12-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutforheritage_abouthero_bottomgallery_topgallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='detail_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='About/board_members/details/'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='detail_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='e.g. Facebook, Twitter', max_length=50)),
                ('url', models.URLField()),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='about.boardmember')),
            ],
        ),
    ]
