# Generated by Django 5.2.8 on 2025-12-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_boardmember_detail_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottomgallery',
            old_name='top_image',
            new_name='bottom_image',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='detail_image',
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='About/board_members/details/')),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='about.boardmember')),
            ],
        ),
    ]
