# Generated by Django 6.0 on 2026-01-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_top_image_bottomgallery_bottom_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about/president')),
                ('designation', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('socialmedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.socialmedialink')),
            ],
        ),
    ]
