# Generated by Django 6.0 on 2026-01-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_president'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='president',
            name='socialmedia',
        ),
        migrations.AlterField(
            model_name='president',
            name='image',
            field=models.ImageField(upload_to='About/president'),
        ),
        migrations.CreateModel(
            name='PresidentSocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='about.president')),
            ],
        ),
    ]
