# Generated by Django 6.0 on 2026-01-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_president_socialmedia_alter_president_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='image',
            field=models.ImageField(upload_to='about/president'),
        ),
    ]
