# Generated by Django 5.2.8 on 2026-02-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_president_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottomgallery',
            options={'verbose_name': 'Bottom Gallery', 'verbose_name_plural': 'Bottom Gallery'},
        ),
        migrations.AlterModelOptions(
            name='topgallery',
            options={'verbose_name': 'Top Gallery', 'verbose_name_plural': 'Top Gallery'},
        ),
        migrations.AlterField(
            model_name='membertype',
            name='type_name',
            field=models.CharField(choices=[('board_of_director', 'Board of Directors'), ('executive_member', 'Executive Member'), ('founder_member', 'Founder Member')], max_length=50, unique=True),
        ),
    ]
