# Generated by Django 5.2.8 on 2026-03-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_bottomgallery_options_alter_topgallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('beyond_thinking', 'Beyond Thinking'), ('beyond_thinking_left', 'Beyond Thinking Left'), ('beyond_thinking_right', 'Beyond Thinking Right')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Club History',
                'verbose_name_plural': 'Club History',
            },
        ),
        migrations.CreateModel(
            name='BeyondThinking',
            fields=[
            ],
            options={
                'verbose_name': 'Beyond Thinking',
                'verbose_name_plural': 'Beyond Thinking',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.clubhistory',),
        ),
        migrations.CreateModel(
            name='BeyondThinkingLeft',
            fields=[
            ],
            options={
                'verbose_name': 'Beyond Thinking Left',
                'verbose_name_plural': 'Beyond Thinking Left',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.clubhistory',),
        ),
        migrations.CreateModel(
            name='BeyondThinkingRight',
            fields=[
            ],
            options={
                'verbose_name': 'Beyond Thinking Right',
                'verbose_name_plural': 'Beyond Thinking Right',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('about.clubhistory',),
        ),
        migrations.CreateModel(
            name='ClubHistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/club_history/')),
                ('club_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.clubhistory')),
            ],
            options={
                'verbose_name': 'Club History Image',
                'verbose_name_plural': 'Club History Images',
            },
        ),
    ]
