# Generated by Django 5.2.8 on 2025-12-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='designation',
            field=models.TextField(),
        ),
    ]
