# Generated by Django 5.2.8 on 2025-12-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_facilities_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubevents',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='home/club'),
        ),
    ]
