# Generated by Django 6.0 on 2025-12-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clubevents_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directors',
        ),
        migrations.DeleteModel(
            name='DirectorsHead',
        ),
        migrations.DeleteModel(
            name='President',
        ),
    ]
