# Generated by Django 6.0 on 2026-01-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_moments_momentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('gallery_type', models.CharField(choices=[('memberships', 'Memberships'), ('reservation', 'Reservation'), ('menu', 'Menu')], db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diningimage',
            name='dining',
        ),
        migrations.RemoveField(
            model_name='memoriesimage',
            name='memories',
        ),
        migrations.RemoveField(
            model_name='momentimage',
            name='moments',
        ),
        migrations.RemoveField(
            model_name='signatureimage',
            name='signature',
        ),
        migrations.CreateModel(
            name='MembershipGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Membership Gallery',
                'verbose_name_plural': 'Membership Gallery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallery',),
        ),
        migrations.CreateModel(
            name='MenuGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Menu Gallery',
                'verbose_name_plural': 'Menu Gallery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallery',),
        ),
        migrations.CreateModel(
            name='ReservationGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Reservation Gallery',
                'verbose_name_plural': 'Reservation Gallery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallery',),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallery')),
            ],
        ),
        migrations.DeleteModel(
            name='Dining',
        ),
        migrations.DeleteModel(
            name='DiningImage',
        ),
        migrations.DeleteModel(
            name='Memories',
        ),
        migrations.DeleteModel(
            name='MemoriesImage',
        ),
        migrations.DeleteModel(
            name='MomentImage',
        ),
        migrations.DeleteModel(
            name='Moments',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
        migrations.DeleteModel(
            name='SignatureImage',
        ),
    ]
