# Generated by Django 6.0 on 2026-01-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallery_remove_diningimage_dining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('memberships', 'Memberships'), ('reservation', 'Reservation'), ('menu', 'Menu')], db_index=True, max_length=30)),
                ('section_type', models.CharField(choices=[('fine_dining', 'Fine Dining & Signature Experiences'), ('live_music', 'Live Music Shows & Unforgettable Memories'), ('fine_dining_2', 'Fine Dining & Signature Experiences (Second)')], db_index=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFineDining',
            fields=[
            ],
            options={
                'verbose_name': 'Memberships - Fine Dining',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='MembershipFineDiningSecond',
            fields=[
            ],
            options={
                'verbose_name': 'Memberships - Fine Dining (Second)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='MembershipLiveMusic',
            fields=[
            ],
            options={
                'verbose_name': 'Memberships - Live Music',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='MenuFineDining',
            fields=[
            ],
            options={
                'verbose_name': 'Menu - Fine Dining',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='MenuFineDiningSecond',
            fields=[
            ],
            options={
                'verbose_name': 'Menu - Fine Dining (Second)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='MenuLiveMusic',
            fields=[
            ],
            options={
                'verbose_name': 'Menu - Live Music',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='ReservationFineDining',
            fields=[
            ],
            options={
                'verbose_name': 'Reservation - Fine Dining',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='ReservationFineDiningSecond',
            fields=[
            ],
            options={
                'verbose_name': 'Reservation - Fine Dining (Second)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='ReservationLiveMusic',
            fields=[
            ],
            options={
                'verbose_name': 'Reservation - Live Music',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.gallerysection',),
        ),
        migrations.CreateModel(
            name='GallerySectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experience/images/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerysection')),
            ],
        ),
    ]
