# Generated by Django 5.2.8 on 2025-12-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerbrand',
            name='short_text',
            field=models.TextField(),
        ),
    ]
