# Generated by Django 5.2.8 on 2025-12-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_alter_footerbrand_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(upload_to='Footer/social-icon'),
        ),
    ]
