# Generated by Django 5.2.8 on 2025-12-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Accommodation/card')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('room_size', models.FloatField(blank=True, null=True)),
                ('bed_size', models.CharField(blank=True, max_length=50, null=True)),
                ('guests', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation_Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='accommodation/hero')),
                ('title', models.CharField(max_length=255)),
                ('sub_Title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='accommodation/banner')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='below_impressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='accommodation/impressions')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='accommodation/gallery')),
                ('below_image', models.ImageField(blank=True, null=True, upload_to='accommodation/gallery')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Luxuey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation/gallery')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.ImageField(blank=True, null=True, upload_to='accommodation/provide')),
                ('service_name', models.CharField(max_length=255)),
                ('short_descriptions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Impressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='accommodation/impressions/logo')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('impressions_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.below_impressions')),
            ],
        ),
    ]
