# Generated by Django 5.2.8 on 2025-12-03 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='accommodation/hero')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='accommodation/banner')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BelowImpressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='accommodation/impressions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='accommodation/gallery')),
                ('below_image', models.ImageField(blank=True, null=True, upload_to='accommodation/gallery')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='accommodation/gallery')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='Accommodation_Hero',
        ),
        migrations.DeleteModel(
            name='Banner_image',
        ),
        migrations.DeleteModel(
            name='Gallery_image',
        ),
        migrations.DeleteModel(
            name='Luxuey',
        ),
        migrations.AddField(
            model_name='impressions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impressions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='provide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='impressions',
            name='impressions_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.belowimpressions'),
        ),
        migrations.DeleteModel(
            name='below_impressions',
        ),
    ]
