# Generated by Django 5.2.8 on 2025-12-03 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodationhero_bannerimage_belowimpressions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belowimpressions',
            name='images',
        ),
        migrations.RemoveField(
            model_name='impressions',
            name='impressions_image',
        ),
        migrations.AddField(
            model_name='belowimpressions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation/impressions/images/'),
        ),
        migrations.AddField(
            model_name='belowimpressions',
            name='impression',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodation.impressions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impressions',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation/impressions/logo/'),
        ),
    ]
