# Generated by Django 5.2.8 on 2025-12-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_remove_belowimpressions_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BelowImpressions',
            new_name='ImpressionsImages',
        ),
    ]
