# Generated by Django 6.0 on 2025-12-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_rename_belowimpressions_impressionsimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provide',
            name='short_descriptions',
            field=models.TextField(),
        ),
    ]
