# Generated by Django 5.2.8 on 2026-03-08 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0005_alter_provide_short_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('area', models.PositiveIntegerField(help_text='Area in m²')),
                ('bed_type', models.CharField(max_length=255)),
                ('max_guests', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodation/suites/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodation.suite')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
