# Generated by Django 5.2.8 on 2026-03-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0006_suite_suiteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvideHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_text', models.CharField(default='Select Your Best Suites', max_length=255)),
                ('descriptions', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuiteHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_text', models.CharField(default='Select Your Best Suites', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='provide',
            name='provide_descriptions',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='suite',
            name='area_icon',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation/suites/icons/'),
        ),
        migrations.AddField(
            model_name='suite',
            name='bed_icon',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation/suites/icons/'),
        ),
        migrations.AddField(
            model_name='suite',
            name='guest_icon',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation/suites/icons/'),
        ),
        migrations.AddField(
            model_name='provide',
            name='provide_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provide', to='accommodation.providehead'),
        ),
        migrations.AddField(
            model_name='suite',
            name='suite_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite', to='accommodation.suitehead'),
        ),
    ]
