# Generated by Django 5.2.8 on 2026-03-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0007_providehead_suitehead_provide_provide_descriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provide',
            name='provide_descriptions',
        ),
    ]
